#include "InstructionSet.h"


Instruction::Instruction(byte opcode, wstring_view name, bool illegal, LabelAccess labelAccess, OperandMode mode) : opcode(opcode), name(name), illegal(illegal), labelAccess(labelAccess), mode(mode) {

};


byte Instruction::GetOpcode() const {
    return opcode;
}


wstring_view Instruction::GetName() const {
    return name;
}

/*
** find the length of an op-code
*/
unsigned short Instruction::GetLength() const {

    switch (mode) {
    case OperandMode::Immediate:
    case OperandMode::ZeroPage:
    case OperandMode::IndexedIndirect:
    case OperandMode::IndirectIndexed:
    case OperandMode::ZeroPageX:
    case OperandMode::ZeroPageY:
    case OperandMode::Relative:
        return 2;

    case OperandMode::Absolute:
    case OperandMode::AbsoluteX:
    case OperandMode::AbsoluteY:
    case OperandMode::Indirect:
        return 3;

    default:
        return 1;
    }
}

LabelAccess Instruction::GetLabelAccess() const {
    return labelAccess;
}

OperandMode Instruction::GetOperandMode() const {
    return mode;
}

bool Instruction::IsImmediateMode() const {
    return mode == OperandMode::Immediate;
}

bool Instruction::IsUnsupportedInstruction() const {
    return illegal;
}

InstructionSet::InstructionSet(wstring_view name, std::array<Instruction, 256> instructionArray) : name(name), instructionArray(instructionArray) {
}

InstructionSetMOS6502::InstructionSetMOS6502(wstring_view name) : InstructionSet(name,
    // Mnemonics for legal opcodes are given in upper case. 
    // Mnemonics for illegal opcodes are given in lower case.
    {
        {

            { 0x00, L"BRK", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x01, L"ORA", false, LabelAccess::READ, OperandMode::IndexedIndirect },
            { 0x02, L"cim", true, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x03, L"aso", true, LabelAccess::WRITE, OperandMode::IndirectIndexed },
            { 0x04, L"dop", true, LabelAccess::READ_WRITE, OperandMode::ZeroPage },
            { 0x05, L"ORA", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0x06, L"ASL", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x07, L"aso", true, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x08, L"PHP", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x09, L"ORA", false, LabelAccess::READ, OperandMode::Immediate },
            { 0x0A, L"ASL", false, LabelAccess::READ_WRITE, OperandMode::Accumulator },
            { 0x0B, L"anc", true, LabelAccess::READ_WRITE, OperandMode::Immediate },
            { 0x0C, L"top", true, LabelAccess::READ_WRITE, OperandMode::Absolute },
            { 0x0D, L"ORA", false, LabelAccess::READ, OperandMode::Absolute },
            { 0x0E, L"ASL", false, LabelAccess::WRITE, OperandMode::Absolute },
            { 0x0F, L"aso", true, LabelAccess::WRITE, OperandMode::Absolute },
            { 0x10, L"BPL", false, LabelAccess::READ_WRITE, OperandMode::Relative },
            { 0x11, L"ORA", false, LabelAccess::READ, OperandMode::IndirectIndexed },
            { 0x12, L"cim", true, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x13, L"aso", true, LabelAccess::WRITE, OperandMode::IndexedIndirect },
            { 0x14, L"dop", true, LabelAccess::READ_WRITE, OperandMode::ZeroPageX },
            { 0x15, L"ORA", false, LabelAccess::READ, OperandMode::ZeroPageX },
            { 0x16, L"ASL", false, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0x17, L"aso", true, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0x18, L"CLC", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x19, L"ORA", false, LabelAccess::READ, OperandMode::AbsoluteY },
            { 0x1A, L"npo", true, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x1B, L"aso", true, LabelAccess::WRITE, OperandMode::AbsoluteY },
            { 0x1C, L"top", true, LabelAccess::READ_WRITE, OperandMode::AbsoluteX },
            { 0x1D, L"ORA", false, LabelAccess::READ, OperandMode::AbsoluteX },
            { 0x1E, L"ASL", false, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0x1F, L"aso", true, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0x20, L"JSR", false, LabelAccess::READ_WRITE, OperandMode::Absolute },
            { 0x21, L"AND", false, LabelAccess::READ, OperandMode::IndexedIndirect },
            { 0x22, L"cim", true, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x23, L"rln", true, LabelAccess::WRITE, OperandMode::IndexedIndirect },
            { 0x24, L"BIT", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0x25, L"AND", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0x26, L"ROL", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x27, L"rln", true, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x28, L"PLP", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x29, L"AND", false, LabelAccess::READ_WRITE, OperandMode::Immediate },
            { 0x2A, L"ROL", false, LabelAccess::READ_WRITE, OperandMode::Accumulator },
            { 0x2B, L"anc", true, LabelAccess::READ_WRITE, OperandMode::Immediate },
            { 0x2C, L"BIT", false, LabelAccess::READ, OperandMode::Absolute },
            { 0x2D, L"AND", false, LabelAccess::READ, OperandMode::Absolute },
            { 0x2E, L"ROL", false, LabelAccess::WRITE, OperandMode::Absolute },
            { 0x2F, L"rln", true, LabelAccess::WRITE, OperandMode::Absolute },
            { 0x30, L"BMI", false, LabelAccess::READ_WRITE, OperandMode::Relative },
            { 0x31, L"AND", false, LabelAccess::READ, OperandMode::IndirectIndexed },
            { 0x32, L"cim", true, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x33, L"rln", true, LabelAccess::WRITE, OperandMode::IndirectIndexed },
            { 0x34, L"dop", true, LabelAccess::READ_WRITE, OperandMode::ZeroPageX },
            { 0x35, L"AND", false, LabelAccess::READ_WRITE, OperandMode::ZeroPageX },
            { 0x36, L"ROL", false, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0x37, L"rln", true, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0x38, L"SEC", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x39, L"AND", false, LabelAccess::READ, OperandMode::AbsoluteY },
            { 0x3A, L"npo", true, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x3B, L"rln", true, LabelAccess::WRITE, OperandMode::AbsoluteY },
            { 0x3C, L"top", true, LabelAccess::READ_WRITE, OperandMode::AbsoluteX },
            { 0x3D, L"AND", false, LabelAccess::READ, OperandMode::AbsoluteX },
            { 0x3E, L"ROL", false, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0x3F, L"rln", true, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0x40, L"RTI", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x41, L"EOR", false, LabelAccess::READ, OperandMode::IndexedIndirect },
            { 0x42, L"cim", true, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x43, L"lse", true, LabelAccess::WRITE, OperandMode::IndexedIndirect },
            { 0x44, L"dop", true, LabelAccess::READ_WRITE, OperandMode::ZeroPage },
            { 0x45, L"EOR", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0x46, L"LSR", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x47, L"lse", true, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x48, L"PHA", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x49, L"EOR", false, LabelAccess::READ, OperandMode::Immediate },
            { 0x4A, L"LSR", false, LabelAccess::READ_WRITE, OperandMode::Accumulator },
            { 0x4B, L"alr", true, LabelAccess::READ, OperandMode::Immediate },
            { 0x4C, L"JMP", false, LabelAccess::READ_WRITE, OperandMode::Absolute },
            { 0x4D, L"EOR", false, LabelAccess::READ, OperandMode::Absolute },
            { 0x4E, L"LSR", false, LabelAccess::WRITE, OperandMode::Absolute },
            { 0x4F, L"lse", true, LabelAccess::WRITE, OperandMode::Absolute },
            { 0x50, L"BVC", false, LabelAccess::READ_WRITE, OperandMode::Relative },
            { 0x51, L"EOR", false, LabelAccess::READ, OperandMode::IndirectIndexed },
            { 0x52, L"cim", true, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x53, L"lse", true, LabelAccess::WRITE, OperandMode::IndirectIndexed },
            { 0x54, L"dop", true, LabelAccess::READ_WRITE, OperandMode::ZeroPageX },
            { 0x55, L"EOR", false, LabelAccess::READ, OperandMode::ZeroPageX },
            { 0x56, L"LSR", false, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0x57, L"lse", true, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0x58, L"CLI", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x59, L"EOR", false, LabelAccess::READ, OperandMode::AbsoluteY },
            { 0x5A, L"npo", true, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x5B, L"lse", true, LabelAccess::WRITE, OperandMode::AbsoluteY },
            { 0x5C, L"top", true, LabelAccess::READ_WRITE, OperandMode::AbsoluteX },
            { 0x5D, L"EOR", false, LabelAccess::READ, OperandMode::AbsoluteX },
            { 0x5E, L"LSR", false, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0x5F, L"lse", true, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0x60, L"RTS", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x61, L"ADC", false, LabelAccess::READ, OperandMode::IndexedIndirect },
            { 0x62, L"cim", true, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x63, L"rrd", true, LabelAccess::WRITE, OperandMode::IndexedIndirect },
            { 0x64, L"dop", true, LabelAccess::READ_WRITE, OperandMode::ZeroPage },
            { 0x65, L"ADC", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0x66, L"ROR", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x67, L"rrd", true, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x68, L"PLA", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x69, L"ADC", false, LabelAccess::READ, OperandMode::Immediate },
            { 0x6A, L"ROR", false, LabelAccess::READ_WRITE, OperandMode::Accumulator },
            { 0x6B, L"arr", true, LabelAccess::READ_WRITE, OperandMode::Immediate },
            { 0x6C, L"JMP", false, LabelAccess::READ_WRITE, OperandMode::Indirect },
            { 0x6D, L"ADC", false, LabelAccess::READ, OperandMode::Absolute },
            { 0x6E, L"ROR", false, LabelAccess::WRITE, OperandMode::Absolute },
            { 0x6F, L"rrd", true, LabelAccess::WRITE, OperandMode::Absolute },
            { 0x70, L"BVS", false, LabelAccess::READ_WRITE, OperandMode::Relative },
            { 0x71, L"ADC", false, LabelAccess::READ, OperandMode::IndirectIndexed },
            { 0x72, L"cim", true, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x73, L"rrd", true, LabelAccess::WRITE, OperandMode::IndirectIndexed },
            { 0x74, L"dop", true, LabelAccess::READ_WRITE, OperandMode::ZeroPageX },
            { 0x75, L"ADC", false, LabelAccess::READ, OperandMode::ZeroPageX },
            { 0x76, L"ROR", false, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0x77, L"rrd", true, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0x78, L"SEI", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x79, L"ADC", false, LabelAccess::READ, OperandMode::AbsoluteY },
            { 0x7A, L"npo", true, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x7B, L"rrd", true, LabelAccess::WRITE, OperandMode::AbsoluteY },
            { 0x7C, L"top", true, LabelAccess::READ_WRITE, OperandMode::AbsoluteX },
            { 0x7D, L"ADC", false, LabelAccess::READ, OperandMode::AbsoluteX },
            { 0x7E, L"ROR", false, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0x7F, L"rrd", true, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0x80, L"dop", true, LabelAccess::READ_WRITE, OperandMode::Immediate },
            { 0x81, L"STA", false, LabelAccess::WRITE, OperandMode::IndexedIndirect },
            { 0x82, L"dop", true, LabelAccess::READ_WRITE, OperandMode::Immediate },
            { 0x83, L"sax", true, LabelAccess::WRITE, OperandMode::IndexedIndirect },
            { 0x84, L"STY", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x85, L"STA", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x86, L"STX", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x87, L"sax", true, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x88, L"DEY", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x89, L"dop", true, LabelAccess::READ_WRITE, OperandMode::Immediate },
            { 0x8A, L"TXA", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x8B, L"ane", true, LabelAccess::READ_WRITE, OperandMode::Immediate },
            { 0x8C, L"STY", false, LabelAccess::WRITE, OperandMode::Absolute },
            { 0x8D, L"STA", false, LabelAccess::WRITE, OperandMode::Absolute },
            { 0x8E, L"STX", false, LabelAccess::WRITE, OperandMode::Absolute },
            { 0x8F, L"sax", true, LabelAccess::WRITE, OperandMode::Absolute },
            { 0x90, L"BCC", false, LabelAccess::READ_WRITE, OperandMode::Relative },
            { 0x91, L"STA", false, LabelAccess::WRITE, OperandMode::IndirectIndexed },
            { 0x92, L"cim", true, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x93, L"sha", true, LabelAccess::WRITE, OperandMode::IndirectIndexed },
            { 0x94, L"STY", false, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0x95, L"STA", false, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0x96, L"STX", false, LabelAccess::WRITE, OperandMode::ZeroPageY },
            { 0x97, L"sha", true, LabelAccess::WRITE, OperandMode::ZeroPageY },
            { 0x98, L"TYA", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x99, L"STA", false, LabelAccess::WRITE, OperandMode::AbsoluteY },
            { 0x9A, L"TXS", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x9B, L"shs", true, LabelAccess::WRITE, OperandMode::AbsoluteY },
            { 0x9C, L"shy", true, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0x9D, L"STA", false, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0x9E, L"shx", true, LabelAccess::WRITE, OperandMode::AbsoluteY },
            { 0x9F, L"axa", true, LabelAccess::WRITE, OperandMode::AbsoluteY },
            { 0xA0, L"LDY", false, LabelAccess::READ, OperandMode::Immediate },
            { 0xA1, L"LDA", false, LabelAccess::READ, OperandMode::IndexedIndirect },
            { 0xA2, L"LDX", false, LabelAccess::READ, OperandMode::Immediate },
            { 0xA3, L"lax", true, LabelAccess::READ, OperandMode::IndexedIndirect },
            { 0xA4, L"LDY", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0xA5, L"LDA", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0xA6, L"LDX", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0xA7, L"lax", true, LabelAccess::READ, OperandMode::ZeroPage },
            { 0xA8, L"TAY", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xA9, L"LDA", false, LabelAccess::READ, OperandMode::Immediate },
            { 0xAA, L"TAX", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xAB, L"anx", true, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xAC, L"LDY", false, LabelAccess::READ, OperandMode::Absolute },
            { 0xAD, L"LDA", false, LabelAccess::READ, OperandMode::Absolute },
            { 0xAE, L"LDX", false, LabelAccess::READ, OperandMode::Absolute },
            { 0xAF, L"lax", true, LabelAccess::READ, OperandMode::Absolute },
            { 0xB0, L"BCS", false, LabelAccess::READ_WRITE, OperandMode::Relative },
            { 0xB1, L"LDA", false, LabelAccess::READ, OperandMode::IndirectIndexed },
            { 0xB2, L"cim", true, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xB3, L"lax", true, LabelAccess::READ, OperandMode::IndirectIndexed },
            { 0xB4, L"LDY", false, LabelAccess::READ, OperandMode::ZeroPageX },
            { 0xB5, L"LDA", false, LabelAccess::READ, OperandMode::ZeroPageX },
            { 0xB6, L"LDX", false, LabelAccess::READ, OperandMode::ZeroPageY },
            { 0xB7, L"lax", true, LabelAccess::READ, OperandMode::ZeroPageY },
            { 0xB8, L"CLV", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xB9, L"LDA", false, LabelAccess::READ, OperandMode::AbsoluteY },
            { 0xBA, L"TSX", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xBB, L"las", true, LabelAccess::READ, OperandMode::AbsoluteY },
            { 0xBC, L"LDY", false, LabelAccess::READ, OperandMode::AbsoluteX },
            { 0xBD, L"LDA", false, LabelAccess::READ, OperandMode::AbsoluteX },
            { 0xBE, L"LDX", false, LabelAccess::READ, OperandMode::AbsoluteY },
            { 0xBF, L"lax", true, LabelAccess::READ, OperandMode::AbsoluteY },
            { 0xC0, L"CPY", false, LabelAccess::READ, OperandMode::Immediate },
            { 0xC1, L"CMP", false, LabelAccess::READ, OperandMode::IndexedIndirect },
            { 0xC2, L"dop", true, LabelAccess::READ_WRITE, OperandMode::Immediate },
            { 0xC3, L"dcp", true, LabelAccess::WRITE, OperandMode::IndexedIndirect },
            { 0xC4, L"CPY", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0xC5, L"CMP", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0xC6, L"DEC", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0xC7, L"dcp", true, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0xC8, L"INY", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xC9, L"CMP", false, LabelAccess::READ, OperandMode::Immediate },
            { 0xCA, L"DEX", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xCB, L"sbx", true, LabelAccess::READ_WRITE, OperandMode::Immediate },
            { 0xCC, L"CPY", false, LabelAccess::READ, OperandMode::Absolute },
            { 0xCD, L"CMP", false, LabelAccess::READ, OperandMode::Absolute },
            { 0xCE, L"DEC", false, LabelAccess::WRITE, OperandMode::Absolute },
            { 0xCF, L"dcp", true, LabelAccess::WRITE, OperandMode::Absolute },
            { 0xD0, L"BNE", false, LabelAccess::READ_WRITE, OperandMode::Relative },
            { 0xD1, L"CMP", false, LabelAccess::READ, OperandMode::IndirectIndexed },
            { 0xD2, L"cim", true, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xD3, L"dcp", true, LabelAccess::WRITE, OperandMode::IndirectIndexed },
            { 0xD4, L"dop", true, LabelAccess::READ_WRITE, OperandMode::ZeroPageX },
            { 0xD5, L"CMP", false, LabelAccess::READ, OperandMode::ZeroPageX },
            { 0xD6, L"DEC", false, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0xD7, L"dcp", true, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0xD8, L"CLD", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xD9, L"CMP", false, LabelAccess::READ, OperandMode::AbsoluteY },
            { 0xDA, L"npo", true, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xDB, L"dcp", true, LabelAccess::WRITE, OperandMode::AbsoluteY },
            { 0xDC, L"top", true, LabelAccess::READ_WRITE, OperandMode::AbsoluteX },
            { 0xDD, L"CMP", false, LabelAccess::READ, OperandMode::AbsoluteX },
            { 0xDE, L"DEC", false, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0xDF, L"dcp", true, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0xE0, L"CPX", false, LabelAccess::READ, OperandMode::Immediate },
            { 0xE1, L"SBC", false, LabelAccess::READ, OperandMode::IndexedIndirect },
            { 0xE2, L"dop", true, LabelAccess::READ_WRITE, OperandMode::Immediate },
            { 0xE3, L"isb", true, LabelAccess::WRITE, OperandMode::IndexedIndirect },
            { 0xE4, L"CPX", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0xE5, L"SBC", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0xE6, L"INC", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0xE7, L"isb", true, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0xE8, L"INX", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xE9, L"SBC", false, LabelAccess::READ_WRITE, OperandMode::Immediate },
            { 0xEA, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xEB, L"sbc", true, LabelAccess::READ, OperandMode::Immediate },
            { 0xEC, L"CPX", false, LabelAccess::READ, OperandMode::Absolute },
            { 0xED, L"SBC", false, LabelAccess::READ, OperandMode::Absolute },
            { 0xEE, L"INC", false, LabelAccess::WRITE, OperandMode::Absolute },
            { 0xEF, L"isb", true, LabelAccess::WRITE, OperandMode::Absolute },
            { 0xF0, L"BEQ", false, LabelAccess::READ_WRITE, OperandMode::Relative },
            { 0xF1, L"SBC", false, LabelAccess::READ, OperandMode::IndirectIndexed },
            { 0xF2, L"cim", true, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xF3, L"isb", true, LabelAccess::WRITE, OperandMode::IndirectIndexed },
            { 0xF4, L"dop", true, LabelAccess::READ_WRITE, OperandMode::ZeroPageX },
            { 0xF5, L"SBC", false, LabelAccess::READ, OperandMode::ZeroPageX },
            { 0xF6, L"INC", false, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0xF7, L"isb", true, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0xF8, L"SED", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xF9, L"SBC", false, LabelAccess::READ, OperandMode::AbsoluteY },
            { 0xFA, L"npo", true, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xFB, L"isb", true, LabelAccess::WRITE, OperandMode::AbsoluteY },
            { 0xFC, L"top", true, LabelAccess::READ_WRITE, OperandMode::AbsoluteX },
            { 0xFD, L"SBC", false, LabelAccess::READ, OperandMode::AbsoluteX },
            { 0xFE, L"INC", false, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0xFF, L"isb", true, LabelAccess::WRITE, OperandMode::AbsoluteX }
                }
    }
) {
};

InstructionSetMOS65C02::InstructionSetMOS65C02(wstring_view name) : InstructionSet(name,
    // All mnemonics are considered legal even reserved NOPs.
    // Reserved NOPs should be ouput as .BYTE $xx[,$yy[,$zz]] in the disassembly listing
    {
        {

            { 0x00, L"BRK", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x01, L"ORA", false, LabelAccess::READ, OperandMode::IndexedIndirect },
            { 0x02, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::ReservedNop2Byte },
            { 0x03, L"NOP", false, LabelAccess::WRITE, OperandMode::ReservedNop1Byte },
            { 0x04, L"TSB", false, LabelAccess::READ_WRITE, OperandMode::ZeroPage },
            { 0x05, L"ORA", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0x06, L"ASL", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x07, L"RMB0", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x08, L"PHP", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x09, L"ORA", false, LabelAccess::READ, OperandMode::Immediate },
            { 0x0A, L"ASL", false, LabelAccess::READ_WRITE, OperandMode::Accumulator },
            { 0x0B, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::ReservedNop1Byte },
            { 0x0C, L"TSB", false, LabelAccess::READ_WRITE, OperandMode::Absolute },
            { 0x0D, L"ORA", false, LabelAccess::READ, OperandMode::Absolute },
            { 0x0E, L"ASL", false, LabelAccess::WRITE, OperandMode::Absolute },
            { 0x0F, L"BBR0", false, LabelAccess::WRITE, OperandMode::ZeroPageRelative },
            { 0x10, L"BPL", false, LabelAccess::READ_WRITE, OperandMode::Relative },
            { 0x11, L"ORA", false, LabelAccess::READ, OperandMode::IndirectIndexed },
            { 0x12, L"ORA", false, LabelAccess::READ_WRITE, OperandMode::ZeroPageIndirect },
            { 0x13, L"NOP", false, LabelAccess::WRITE, OperandMode::ReservedNop1Byte },
            { 0x14, L"TRB", false, LabelAccess::READ_WRITE, OperandMode::ZeroPage },
            { 0x15, L"ORA", false, LabelAccess::READ, OperandMode::ZeroPageX },
            { 0x16, L"ASL", false, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0x17, L"RMB1", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x18, L"CLC", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x19, L"ORA", false, LabelAccess::READ, OperandMode::AbsoluteY },
            { 0x1A, L"INC", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x1B, L"NOP", false, LabelAccess::WRITE, OperandMode::ReservedNop1Byte },
            { 0x1C, L"TRB", false, LabelAccess::READ_WRITE, OperandMode::Absolute },
            { 0x1D, L"ORA", false, LabelAccess::READ, OperandMode::AbsoluteX },
            { 0x1E, L"ASL", false, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0x1F, L"BBR1", false, LabelAccess::WRITE, OperandMode::ZeroPageRelative },
            { 0x20, L"JSR", false, LabelAccess::READ_WRITE, OperandMode::Absolute },
            { 0x21, L"AND", false, LabelAccess::READ, OperandMode::IndexedIndirect },
            { 0x22, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::ReservedNop2Byte },
            { 0x23, L"NOP", false, LabelAccess::WRITE, OperandMode::ReservedNop1Byte },
            { 0x24, L"BIT", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0x25, L"AND", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0x26, L"ROL", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x27, L"RMB2", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x28, L"PLP", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x29, L"AND", false, LabelAccess::READ_WRITE, OperandMode::Immediate },
            { 0x2A, L"ROL", false, LabelAccess::READ_WRITE, OperandMode::Accumulator },
            { 0x2B, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::ReservedNop1Byte },
            { 0x2C, L"BIT", false, LabelAccess::READ, OperandMode::Absolute },
            { 0x2D, L"AND", false, LabelAccess::READ, OperandMode::Absolute },
            { 0x2E, L"ROL", false, LabelAccess::WRITE, OperandMode::Absolute },
            { 0x2F, L"BBR2", false, LabelAccess::WRITE, OperandMode::ZeroPageRelative },
            { 0x30, L"BMI", false, LabelAccess::READ_WRITE, OperandMode::Relative },
            { 0x31, L"AND", false, LabelAccess::READ, OperandMode::IndirectIndexed },
            { 0x32, L"AND", false, LabelAccess::READ_WRITE, OperandMode::ZeroPageIndirect },
            { 0x33, L"NOP", false, LabelAccess::WRITE, OperandMode::ReservedNop1Byte },
            { 0x34, L"BIT", false, LabelAccess::READ_WRITE, OperandMode::ZeroPageX },
            { 0x35, L"AND", false, LabelAccess::READ_WRITE, OperandMode::ZeroPageX },
            { 0x36, L"ROL", false, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0x37, L"RMB3", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x38, L"SEC", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x39, L"AND", false, LabelAccess::READ, OperandMode::AbsoluteY },
            { 0x3A, L"DEC", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x3B, L"NOP", false, LabelAccess::WRITE, OperandMode::ReservedNop1Byte },
            { 0x3C, L"BIT", false, LabelAccess::READ_WRITE, OperandMode::AbsoluteX },
            { 0x3D, L"AND", false, LabelAccess::READ, OperandMode::AbsoluteX },
            { 0x3E, L"ROL", false, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0x3F, L"BBR3", false, LabelAccess::WRITE, OperandMode::ZeroPageRelative },
            { 0x40, L"RTI", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x41, L"EOR", false, LabelAccess::READ, OperandMode::IndexedIndirect },
            { 0x42, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::ReservedNop2Byte },
            { 0x43, L"NOP", false, LabelAccess::WRITE, OperandMode::ReservedNop1Byte },
            { 0x44, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::ReservedNop2Byte },
            { 0x45, L"EOR", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0x46, L"LSR", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x47, L"RMB4", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x48, L"PHA", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x49, L"EOR", false, LabelAccess::READ, OperandMode::Immediate },
            { 0x4A, L"LSR", false, LabelAccess::READ_WRITE, OperandMode::Accumulator },
            { 0x4B, L"NOP", false, LabelAccess::READ, OperandMode::ReservedNop1Byte },
            { 0x4C, L"JMP", false, LabelAccess::READ_WRITE, OperandMode::Absolute },
            { 0x4D, L"EOR", false, LabelAccess::READ, OperandMode::Absolute },
            { 0x4E, L"LSR", false, LabelAccess::WRITE, OperandMode::Absolute },
            { 0x4F, L"BBR4", false, LabelAccess::WRITE, OperandMode::ZeroPageRelative },
            { 0x50, L"BVC", false, LabelAccess::READ_WRITE, OperandMode::Relative },
            { 0x51, L"EOR", false, LabelAccess::READ, OperandMode::IndirectIndexed },
            { 0x52, L"EOR", false, LabelAccess::READ_WRITE, OperandMode::ZeroPageIndirect },
            { 0x53, L"NOP", false, LabelAccess::WRITE, OperandMode::ReservedNop1Byte },
            { 0x54, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::ReservedNop2Byte },
            { 0x55, L"EOR", false, LabelAccess::READ, OperandMode::ZeroPageX },
            { 0x56, L"LSR", false, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0x57, L"RMB5", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x58, L"CLI", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x59, L"EOR", false, LabelAccess::READ, OperandMode::AbsoluteY },
            { 0x5A, L"PHY", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x5B, L"NOP", false, LabelAccess::WRITE, OperandMode::ReservedNop1Byte },
            { 0x5C, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::ReservedNop3Byte },
            { 0x5D, L"EOR", false, LabelAccess::READ, OperandMode::AbsoluteX },
            { 0x5E, L"LSR", false, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0x5F, L"BBR5", false, LabelAccess::WRITE, OperandMode::ZeroPageRelative },
            { 0x60, L"RTS", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x61, L"ADC", false, LabelAccess::READ, OperandMode::IndexedIndirect },
            { 0x62, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::ReservedNop2Byte },
            { 0x63, L"NOP", false, LabelAccess::WRITE, OperandMode::ReservedNop1Byte },
            { 0x64, L"STZ", false, LabelAccess::READ_WRITE, OperandMode::ZeroPage },
            { 0x65, L"ADC", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0x66, L"ROR", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x67, L"RMB6", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x68, L"PLA", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x69, L"ADC", false, LabelAccess::READ, OperandMode::Immediate },
            { 0x6A, L"ROR", false, LabelAccess::READ_WRITE, OperandMode::Accumulator },
            { 0x6B, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::ReservedNop1Byte },
            { 0x6C, L"JMP", false, LabelAccess::READ_WRITE, OperandMode::Indirect },
            { 0x6D, L"ADC", false, LabelAccess::READ, OperandMode::Absolute },
            { 0x6E, L"ROR", false, LabelAccess::WRITE, OperandMode::Absolute },
            { 0x6F, L"BBR6", false, LabelAccess::WRITE, OperandMode::ZeroPageRelative },
            { 0x70, L"BVS", false, LabelAccess::READ_WRITE, OperandMode::Relative },
            { 0x71, L"ADC", false, LabelAccess::READ, OperandMode::IndirectIndexed },
            { 0x72, L"ADC", false, LabelAccess::READ_WRITE, OperandMode::ZeroPageIndirect },
            { 0x73, L"NOP", false, LabelAccess::WRITE, OperandMode::ReservedNop1Byte },
            { 0x74, L"STZ", false, LabelAccess::READ_WRITE, OperandMode::ZeroPageX },
            { 0x75, L"ADC", false, LabelAccess::READ, OperandMode::ZeroPageX },
            { 0x76, L"ROR", false, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0x77, L"RMB7", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x78, L"SEI", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x79, L"ADC", false, LabelAccess::READ, OperandMode::AbsoluteY },
            { 0x7A, L"PLY", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x7B, L"NOP", false, LabelAccess::WRITE, OperandMode::ReservedNop1Byte },
            { 0x7C, L"JMP", false, LabelAccess::READ_WRITE, OperandMode::IndexedIndirectAbsolute },
            { 0x7D, L"ADC", false, LabelAccess::READ, OperandMode::AbsoluteX },
            { 0x7E, L"ROR", false, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0x7F, L"BBR7", false, LabelAccess::WRITE, OperandMode::ZeroPageRelative },
            { 0x80, L"BRA", false, LabelAccess::READ_WRITE, OperandMode::Relative },
            { 0x81, L"STA", false, LabelAccess::WRITE, OperandMode::IndexedIndirect },
            { 0x82, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::ReservedNop2Byte },
            { 0x83, L"NOP", false, LabelAccess::WRITE, OperandMode::ReservedNop1Byte },
            { 0x84, L"STY", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x85, L"STA", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x86, L"STX", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x87, L"SMB0", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x88, L"DEY", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x89, L"BIT", false, LabelAccess::READ_WRITE, OperandMode::Immediate },
            { 0x8A, L"TXA", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x8B, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::ReservedNop1Byte },
            { 0x8C, L"STY", false, LabelAccess::WRITE, OperandMode::Absolute },
            { 0x8D, L"STA", false, LabelAccess::WRITE, OperandMode::Absolute },
            { 0x8E, L"STX", false, LabelAccess::WRITE, OperandMode::Absolute },
            { 0x8F, L"BBS0", false, LabelAccess::WRITE, OperandMode::ZeroPageRelative },
            { 0x90, L"BCC", false, LabelAccess::READ_WRITE, OperandMode::Relative },
            { 0x91, L"STA", false, LabelAccess::WRITE, OperandMode::IndirectIndexed },
            { 0x92, L"STA", false, LabelAccess::READ_WRITE, OperandMode::ZeroPageIndirect },
            { 0x93, L"NOP", false, LabelAccess::WRITE, OperandMode::ReservedNop1Byte },
            { 0x94, L"STY", false, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0x95, L"STA", false, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0x96, L"STX", false, LabelAccess::WRITE, OperandMode::ZeroPageY },
            { 0x97, L"SMB1", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0x98, L"TYA", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x99, L"STA", false, LabelAccess::WRITE, OperandMode::AbsoluteY },
            { 0x9A, L"TXS", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0x9B, L"NOP", false, LabelAccess::WRITE, OperandMode::ReservedNop1Byte },
            { 0x9C, L"STZ", false, LabelAccess::WRITE, OperandMode::Absolute },
            { 0x9D, L"STA", false, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0x9E, L"STZ", false, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0x9F, L"BBS1", false, LabelAccess::WRITE, OperandMode::ZeroPageRelative },
            { 0xA0, L"LDY", false, LabelAccess::READ, OperandMode::Immediate },
            { 0xA1, L"LDA", false, LabelAccess::READ, OperandMode::IndexedIndirect },
            { 0xA2, L"LDX", false, LabelAccess::READ, OperandMode::Immediate },
            { 0xA3, L"NOP", false, LabelAccess::READ, OperandMode::ReservedNop1Byte },
            { 0xA4, L"LDY", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0xA5, L"LDA", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0xA6, L"LDX", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0xA7, L"SMB2", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0xA8, L"TAY", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xA9, L"LDA", false, LabelAccess::READ, OperandMode::Immediate },
            { 0xAA, L"TAX", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xAB, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::ReservedNop1Byte },
            { 0xAC, L"LDY", false, LabelAccess::READ, OperandMode::Absolute },
            { 0xAD, L"LDA", false, LabelAccess::READ, OperandMode::Absolute },
            { 0xAE, L"LDX", false, LabelAccess::READ, OperandMode::Absolute },
            { 0xAF, L"BBS2", false, LabelAccess::READ, OperandMode::ZeroPageRelative },
            { 0xB0, L"BCS", false, LabelAccess::READ_WRITE, OperandMode::Relative },
            { 0xB1, L"LDA", false, LabelAccess::READ, OperandMode::IndirectIndexed },
            { 0xB2, L"LDA", false, LabelAccess::READ_WRITE, OperandMode::ZeroPageIndirect },
            { 0xB3, L"NOP", false, LabelAccess::READ, OperandMode::ReservedNop1Byte },
            { 0xB4, L"LDY", false, LabelAccess::READ, OperandMode::ZeroPageX },
            { 0xB5, L"LDA", false, LabelAccess::READ, OperandMode::ZeroPageX },
            { 0xB6, L"LDX", false, LabelAccess::READ, OperandMode::ZeroPageY },
            { 0xB7, L"SMB3", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0xB8, L"CLV", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xB9, L"LDA", false, LabelAccess::READ, OperandMode::AbsoluteY },
            { 0xBA, L"TSX", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xBB, L"NOP", false, LabelAccess::READ, OperandMode::ReservedNop1Byte },
            { 0xBC, L"LDY", false, LabelAccess::READ, OperandMode::AbsoluteX },
            { 0xBD, L"LDA", false, LabelAccess::READ, OperandMode::AbsoluteX },
            { 0xBE, L"LDX", false, LabelAccess::READ, OperandMode::AbsoluteY },
            { 0xBF, L"BBS3", false, LabelAccess::READ, OperandMode::ZeroPageRelative },
            { 0xC0, L"CPY", false, LabelAccess::READ, OperandMode::Immediate },
            { 0xC1, L"CMP", false, LabelAccess::READ, OperandMode::IndexedIndirect },
            { 0xC2, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::ReservedNop2Byte },
            { 0xC3, L"NOP", false, LabelAccess::WRITE, OperandMode::ReservedNop1Byte },
            { 0xC4, L"CPY", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0xC5, L"CMP", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0xC6, L"DEC", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0xC7, L"SMB4", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0xC8, L"INY", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xC9, L"CMP", false, LabelAccess::READ, OperandMode::Immediate },
            { 0xCA, L"DEX", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xCB, L"WAI", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xCC, L"CPY", false, LabelAccess::READ, OperandMode::Absolute },
            { 0xCD, L"CMP", false, LabelAccess::READ, OperandMode::Absolute },
            { 0xCE, L"DEC", false, LabelAccess::WRITE, OperandMode::Absolute },
            { 0xCF, L"BBS4", false, LabelAccess::WRITE, OperandMode::ZeroPageRelative },
            { 0xD0, L"BNE", false, LabelAccess::READ_WRITE, OperandMode::Relative },
            { 0xD1, L"CMP", false, LabelAccess::READ, OperandMode::IndirectIndexed },
            { 0xD2, L"CMP", false, LabelAccess::READ_WRITE, OperandMode::ZeroPageIndirect },
            { 0xD3, L"NOP", false, LabelAccess::WRITE, OperandMode::ReservedNop1Byte },
            { 0xD4, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::ReservedNop2Byte },
            { 0xD5, L"CMP", false, LabelAccess::READ, OperandMode::ZeroPageX },
            { 0xD6, L"DEC", false, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0xD7, L"SMB5", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0xD8, L"CLD", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xD9, L"CMP", false, LabelAccess::READ, OperandMode::AbsoluteY },
            { 0xDA, L"PHX", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xDB, L"STP", false, LabelAccess::WRITE, OperandMode::Implied },
            { 0xDC, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::ReservedNop3Byte },
            { 0xDD, L"CMP", false, LabelAccess::READ, OperandMode::AbsoluteX },
            { 0xDE, L"DEC", false, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0xDF, L"BBS5", false, LabelAccess::WRITE, OperandMode::ZeroPageRelative },
            { 0xE0, L"CPX", false, LabelAccess::READ, OperandMode::Immediate },
            { 0xE1, L"SBC", false, LabelAccess::READ, OperandMode::IndexedIndirect },
            { 0xE2, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::ReservedNop2Byte },
            { 0xE3, L"NOP", false, LabelAccess::WRITE, OperandMode::ReservedNop1Byte },
            { 0xE4, L"CPX", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0xE5, L"SBC", false, LabelAccess::READ, OperandMode::ZeroPage },
            { 0xE6, L"INC", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0xE7, L"SMB6", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0xE8, L"INX", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xE9, L"SBC", false, LabelAccess::READ_WRITE, OperandMode::Immediate },
            { 0xEA, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xEB, L"NOP", false, LabelAccess::READ, OperandMode::ReservedNop1Byte },
            { 0xEC, L"CPX", false, LabelAccess::READ, OperandMode::Absolute },
            { 0xED, L"SBC", false, LabelAccess::READ, OperandMode::Absolute },
            { 0xEE, L"INC", false, LabelAccess::WRITE, OperandMode::Absolute },
            { 0xEF, L"BBS6", false, LabelAccess::WRITE, OperandMode::ZeroPageRelative },
            { 0xF0, L"BEQ", false, LabelAccess::READ_WRITE, OperandMode::Relative },
            { 0xF1, L"SBC", false, LabelAccess::READ, OperandMode::IndirectIndexed },
            { 0xF2, L"SBC", false, LabelAccess::READ_WRITE, OperandMode::ZeroPageIndirect },
            { 0xF3, L"NOP", false, LabelAccess::WRITE, OperandMode::ReservedNop1Byte },
            { 0xF4, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::ReservedNop2Byte },
            { 0xF5, L"SBC", false, LabelAccess::READ, OperandMode::ZeroPageX },
            { 0xF6, L"INC", false, LabelAccess::WRITE, OperandMode::ZeroPageX },
            { 0xF7, L"SMB7", false, LabelAccess::WRITE, OperandMode::ZeroPage },
            { 0xF8, L"SED", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xF9, L"SBC", false, LabelAccess::READ, OperandMode::AbsoluteY },
            { 0xFA, L"PLX", false, LabelAccess::READ_WRITE, OperandMode::Implied },
            { 0xFB, L"NOP", false, LabelAccess::WRITE, OperandMode::ReservedNop1Byte },
            { 0xFC, L"NOP", false, LabelAccess::READ_WRITE, OperandMode::ReservedNop3Byte },
            { 0xFD, L"SBC", false, LabelAccess::READ, OperandMode::AbsoluteX },
            { 0xFE, L"INC", false, LabelAccess::WRITE, OperandMode::AbsoluteX },
            { 0xFF, L"BBS7", false, LabelAccess::WRITE, OperandMode::ZeroPageRelative }
        }
    }
) {
};

const std::array<Instruction, 256>& InstructionSet::GetInstructions() const {
    return instructionArray;
}

const Instruction& InstructionSet::GetInstruction(byte opcode) const {
    return instructionArray.at(opcode);
};

const wstring& InstructionSet::GetName() const {
    return name;
}

bool InstructionSet::IsDualAddressingMode(byte opcode) const {
    return opcode == 0xAD || opcode == 0xBD // LDA
        || opcode == 0xAE || opcode == 0xBE // LDX
        || opcode == 0xAC || opcode == 0xBC // LDY
        || opcode == 0x8D || opcode == 0x9D // STA
        || opcode == 0x8E                   // STX
        || opcode == 0x8C                   // SYY
        || opcode == 0x2C                   // BIT
        || opcode == 0x6D || opcode == 0x7D // ADC
        || opcode == 0xED || opcode == 0xFD // SBC
        || opcode == 0x0E || opcode == 0x1E // ASL
        || opcode == 0x4E || opcode == 0x5E // LSR
        || opcode == 0x2E || opcode == 0x3E // ROL
        || opcode == 0x6E || opcode == 0x7E // ROR
        || opcode == 0xCE || opcode == 0xDE // DEC
        || opcode == 0xEE || opcode == 0xFE // INC
        || opcode == 0x0D || opcode == 0x1D // ORA
        || opcode == 0x2D || opcode == 0x3D // AND
        || opcode == 0x4D || opcode == 0x5D // EOR
        ;
}
