#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDB_BITMAP1                             101
#define IDI_DIS6502                             102
#define IDI_EQUATES_CLEAR_USER_EQUATES          103
#define IDI_EQUATES_DEFINE_USER_ADDRESS_RANGE   104
#define IDI_EQUATES_EDIT_USER_EQUATES           105
#define IDI_EQUATES_EXPORT_USER_EQUATES         106
#define IDI_EQUATES_OPEN_USER_EQUATES           107
#define IDI_EQUATES_SAVE_USER_EQUATES           108
#define IDI_FILE_NEW                            109
#define IDI_FILE_OPEN_CASSETTE_IMAGE_FILE       110
#define IDI_FILE_OPEN_DISK_IMAGE_BOOT_SECTORS   111
#define IDI_FILE_OPEN_DISK_IMAGE_EXECUTABLE_FILE 112
#define IDI_FILE_OPEN_DISK_IMAGE_SECTORS        113
#define IDI_FILE_OPEN_EXECUTABLE_FILE           114
#define IDI_FILE_OPEN_RAW_FILE                  115
#define IDI_FILE_OPEN_ROM_IMAGE_FILE            116
#define IDI_FILE_SAVE_DISASSEMBLY_FILES         117
#define IDI_FILE_SAVE_DISK_IMAGE_BOOT_SECTORS   118
#define IDI_HELP_ABOUT                          119
#define IDI_VIEW_PROFILE                        120
#define IDM_DIS_ADDR_RANGE_DEF                  121
#define IDM_DIS_ADDR_RANGE_REF                  122
#define IDM_DIS_BACK_IN_HISTORY                 123
#define IDM_DIS_COMMENT                         124
#define IDM_DIS_FIND                            125
#define IDM_DIS_FIND_DEF                        126
#define IDM_DIS_FIND_NEXT                       127
#define IDM_DIS_FIND_REF1                       128
#define IDM_DIS_FIND_REF2                       129
#define IDM_DIS_RENAME_DEF                      130
#define IDM_DIS_RENAME_REF                      131
#define IDM_DIS_SET_TYPE_CODE                   132
#define IDM_DIS_SET_TYPE_HIBYTE                 133
#define IDM_DIS_SET_TYPE_LOBYTE                 134
#define IDM_DIS_SET_TYPE_STRING                 135
#define IDM_DIS_SET_TYPE_UNKNOWN                136
#define IDM_DUMP_ASSEMBLE                       137
#define IDM_DUMP_COPY_SELECTION                 138
#define IDM_DUMP_CUT_SELECTION                  139
#define IDM_DUMP_DELETE_SELECTION               140
#define IDM_DUMP_EDIT                           141
#define IDM_DUMP_EDIT_COMMENT                   142
#define IDM_DUMP_FIND                           143
#define IDM_DUMP_FIND_NEXT                      144
#define IDM_DUMP_PASTE_AFTER_SELECTION          145
#define IDM_DUMP_PASTE_AT_SELECTION             146
#define IDM_DUMP_QUIT_EDIT                      147
#define IDM_DUMP_SAVE_HEADER                    148
#define IDM_DUMP_SAVE_NO_HEADER                 149
#define IDM_DUMP_SELECT_ALL                     150
#define IDM_DUMP_SELECT_NEXT_UNKNOWN_BLOCK      151
#define IDM_DUMP_SELECT_SPRITES                 152
#define IDM_DUMP_SET_TYPE_BYTE                  153
#define IDM_DUMP_SET_TYPE_CODE                  154
#define IDM_DUMP_SET_TYPE_DLIST                 155
#define IDM_DUMP_SET_TYPE_FIXUP                 156
#define IDM_DUMP_SET_TYPE_HIBYTE                157
#define IDM_DUMP_SET_TYPE_LABEL                 158
#define IDM_DUMP_SET_TYPE_LOBYTE                159
#define IDM_DUMP_SET_TYPE_SBYTE                 160
#define IDM_DUMP_SET_TYPE_STORE                 161
#define IDM_DUMP_SET_TYPE_STRING                162
#define IDM_DUMP_SET_TYPE_SYMBOL                163
#define IDM_DUMP_SET_TYPE_UNKNOWN               164
#define IDM_DUMP_SET_TYPE_WORD                  165
#define IDM_DUMP_SET_UNKNOWN_BLOCK_TO_BYTE      166
#define IDM_DUMP_SPLIT_AT_SELECTION             167
#define IDM_DUMP_START_CODE_TRACE               168
#define IDM_MRU_FILE_1                          169
#define IDM_MRU_FILE_2                          170
#define IDM_MRU_FILE_3                          171
#define IDM_MRU_FILE_4                          172
#define IDM_MRU_FILE_5                          173
#define IDM_MRU_WORKSPACE_1                     174
#define IDM_MRU_WORKSPACE_2                     175
#define IDM_MRU_WORKSPACE_3                     176
#define IDM_MRU_WORKSPACE_4                     177
#define IDM_MRU_WORKSPACE_5                     178
#define IDM_SEGMENT_DELETE                      179
#define IDM_SEGMENT_DOWN                        180
#define IDM_SEGMENT_MERGE                       181
#define IDM_SEGMENT_PROPS                       182
#define IDM_SEGMENT_SAVE_ALL                    183
#define IDM_SEGMENT_SAVE_HEADER                 184
#define IDM_SEGMENT_SAVE_NO_HEADER              185
#define IDM_SEGMENT_UP                          186
#define IDC_ADDRSEGMENT                         1001
#define IDC_BOOTINITADDR                        1002
#define IDC_BOOTLOADADDR                        1003
#define IDC_BYTEPERLINE                         1004
#define IDC_BYTESEPARATOR                       1005
#define IDC_BYTESYNTAX                          1006
#define IDC_CHARPERLINE                         1007
#define IDC_COMMENT                             1008
#define IDC_DISK_IMAGE_EXECUTABLE_FILE_FILES_LIST 1009
#define IDC_DISK_IMAGE_SECTORS_ADDRESS          1010
#define IDC_DISK_IMAGE_SECTORS_SECTORS_LIST     1011
#define IDC_DISK_IMAGE_SECTORS_SECTOR_SCROLL    1012
#define IDC_DSSYNTAX                            1013
#define IDC_ENDSYNTAX                           1014
#define IDC_ENDTAIL                             1015
#define IDC_EQUATES_TEXT                        1016
#define IDC_EQUATE_LINE                         1017
#define IDC_EQUATE_LIST                         1018
#define IDC_EQUATE_RANGE_BASE_EQUATE            1019
#define IDC_EQUATE_RANGE_END_ADDRESS            1020
#define IDC_EQUATE_RANGE_START_ADDRESS          1021
#define IDC_EQUSYNTAX                           1022
#define IDC_FINDASCII                           1023
#define IDC_FINDHEX                             1024
#define IDC_FORCEABSOLUTE                       1025
#define IDC_GRAPHICCOMBO                        1026
#define IDC_HEXNOTATION                         1027
#define IDC_HIBYTE                              1028
#define IDC_HIGHHEADSYNTAX                      1029
#define IDC_HIGHTAILSYNTAX                      1030
#define IDC_INCLUDEHEAD                         1031
#define IDC_INCLUDETAIL                         1032
#define IDC_INSTRUCTION                         1033
#define IDC_LABELPREFIX                         1034
#define IDC_LIST_VERSION                        1035
#define IDC_LOBYTE                              1036
#define IDC_LOWHEADSYNTAX                       1037
#define IDC_LOWTAILSYNTAX                       1038
#define IDC_MAXINCLUDELINES                     1039
#define IDC_ORGSYNTAX                           1040
#define IDC_OUTPUT_ENCODING                     1041
#define IDC_PATH_ASM                            1042
#define IDC_PATH_BIN                            1043
#define IDC_PATH_CAS                            1044
#define IDC_PATH_DSK                            1045
#define IDC_PATH_EQU                            1046
#define IDC_PATH_PRF                            1047
#define IDC_PATH_RAW                            1048
#define IDC_PATH_ROM                            1049
#define IDC_PATH_WRK                            1050
#define IDC_PROCESSORCOMBO                      1051
#define IDC_QUOTEFORASCIISTRINGS                1052
#define IDC_RAW_FILE_ADDRESS                    1053
#define IDC_SBYTESYNTAX                         1054
#define IDC_WORDPERLINE                         1055
#define IDC_WORDSYNTAX                          1056
#define IDC_WORKSPACE_COMPUTER_SYSTEM           1057
#define ID_DIS_BACK_IN_HISTORY                  32771
#define ID_DIS_FIND                             32772
#define ID_DIS_FIND_DEF                         32773
#define ID_DIS_FIND_NEXT                        32774
#define ID_DUMP_ASSEMBLE                        32775
#define ID_DUMP_COPY_SELECTION                  32776
#define ID_DUMP_CUT_SELECTION                   32777
#define ID_DUMP_DELETE_SELECTION                32778
#define ID_DUMP_EDIT                            32779
#define ID_DUMP_FIND                            32780
#define ID_DUMP_FIND_NEXT                       32781
#define ID_DUMP_PASTE_AT_SELECTION              32782
#define ID_DUMP_QUIT_EDIT                       32783
#define ID_DUMP_SELECT                          32784
#define ID_DUMP_SELECT_ALL                      32785
#define ID_DUMP_SELECT_SPRITES                  32786
#define ID_DUMP_START_CODE_TRACE                32787
#define ID_EQUATES_CLEAR_SYSTEM_EQUATES         32788
#define ID_EQUATES_CLEAR_USER_EQUATES           32789
#define ID_EQUATES_DEFINE_USER_ADDRESS_RANGE    32790
#define ID_EQUATES_DISPLAY_SYSTEM_EQUATES       32791
#define ID_EQUATES_EDIT_USER_EQUATES            32792
#define ID_EQUATES_EXPORT_USER_EQUATES          32793
#define ID_EQUATES_OPEN_USER_EQUATES            32794
#define ID_EQUATES_SAVE_USER_EQUATES            32795
#define ID_FILE_ADD_CASSETTE_IMAGE_FILE         32796
#define ID_FILE_ADD_DISK_IMAGE_BOOT_SECTORS     32797
#define ID_FILE_ADD_DISK_IMAGE_EXECUTABLE_FILE  32798
#define ID_FILE_ADD_DISK_IMAGE_SECTORS          32799
#define ID_FILE_ADD_EXECUTABLE_FILE             32800
#define ID_FILE_ADD_RAW_FILE                    32801
#define ID_FILE_ADD_ROM_IMAGE_FILE              32802
#define ID_FILE_EXIT                            32803
#define ID_FILE_NEW                             32804
#define ID_FILE_NEW_WORKSPACE                   32805
#define ID_FILE_OPEN_CASSETTE_IMAGE_FILE        32806
#define ID_FILE_OPEN_DISK_IMAGE_BOOT_SECTORS    32807
#define ID_FILE_OPEN_DISK_IMAGE_EXECUTABLE_FILE 32808
#define ID_FILE_OPEN_DISK_IMAGE_SECTORS         32809
#define ID_FILE_OPEN_EXECUTABLE_FILE            32810
#define ID_FILE_OPEN_RAW_FILE                   32811
#define ID_FILE_OPEN_ROM_IMAGE_FILE             32812
#define ID_FILE_OPEN_WORKSPACE                  32813
#define ID_FILE_SAVE_DISASSEMBLY_FILES          32814
#define ID_FILE_SAVE_DISK_IMAGE_BOOT_SECTORS    32815
#define ID_FILE_SAVE_WORKSPACE                  32816
#define ID_FILE_SAVE_WORKSPACE_AS               32817
#define ID_HELP_ABOUT                           32818
#define ID_VIEW_DEFAULT_FOLDERS                 32819
#define ID_VIEW_DISPLAYASSCREENCODE             32820
#define ID_VIEW_DOUBLE_FONT_HEIGHT              32821
#define ID_VIEW_NODISASSEMBLY                   32822
#define ID_VIEW_PROFILE                         32823
#define IDC_BUTTON_RAW                          40000
#define IDC_CHECKBINARY                         40000
#define IDC_DELETE_EQUATE                       40000
#define IDC_DISK_IMAGE_EXECUTABLE_FILE_DISK_IMAGE_FILE_PATH 40000
#define IDC_DISK_IMAGE_SECTORS_DISK_IMAGE_FILE_PATH 40000
#define IDC_ILLEGALINSTRUCTION                  40000
#define IDC_PASS_NUMBER                         40000
#define IDC_RADIO_ALL                           40000
#define IDC_RAW_FILE_PATH                       40000
#define IDC_SPRITETEXT                          40000
#define IDS_COMPUTER_MEM_ERR                    40000
#define ID_RESULT                               40000
#define IDC_ADD_EQUATE                          40001
#define IDC_ASMADDR                             40001
#define IDC_BUTTON_BIN                          40001
#define IDC_DISK_IMAGE_EXECUTABLE_FILE_FILE_NAME 40001
#define IDC_DISK_IMAGE_SECTORS_SECTORS_LIST_HEADER 40001
#define IDC_RADIO_SELECTED                      40001
#define IDC_RAW_FILE_DUMP                       40001
#define IDC_SEGMENT_NUMBER                      40001
#define IDC_SPRITEWIDTH                         40001
#define IDC_USEHEX                              40001
#define IDS_COMPUTER_NOT_FOUND                  40001
#define IDC_ADDRESSTEXT                         40002
#define IDC_ALIGNINSTRUCTION                    40002
#define IDC_BUTTON_ROM                          40002
#define IDC_DISK_IMAGE_EXECUTABLE_FILE_FILES_LIST_HEADER 40002
#define IDC_DISK_IMAGE_SECTORS_ADD_SECTOR       40002
#define IDS_COMPUTER_NOT_LOADED                 40002
#define ID_OPEN_USER_EQUATES                    40002
#define IDC_ADDRESSSTART                        40003
#define IDC_BUTTON_DSK                          40003
#define IDC_DISK_IMAGE_SECTORS_REMOVE_SECTOR    40003
#define IDC_LINENUMBERING                       40003
#define IDS_DEFAULT_FOLDERS_DIALOG_SUB_TITLE    40003
#define ID_SAVE_USER_EQUATES                    40003
#define IDC_BUTTON_ASM                          40004
#define IDC_DISK_IMAGE_SECTORS_SECTOR_NUMBER    40004
#define IDC_GRAPHICTEXT                         40004
#define IDC_SHOWLOWERCASE                       40004
#define IDS_DEFAULT_FOLDERS_DIALOG_TITLE        40004
#define ID_EXPORT_USER_EQUATES                  40004
#define IDC_BUTTON_WRK                          40005
#define IDC_DISK_IMAGE_SECTORS_SECTOR_DUMP      40005
#define IDC_GRAPHIC                             40005
#define IDC_SHOWIMPLICITE                       40005
#define IDS_DIS_POPUP_MENU_ADDR_RANGE_DEF       40005
#define IDC_BUTTON_EQU                          40006
#define IDC_SHOWCOLON                           40006
#define IDS_DIS_POPUP_MENU_ADDR_RANGE_REF       40006
#define IDC_BUTTON_PRF                          40007
#define IDC_DISPLAYOPCODES                      40007
#define IDS_DIS_POPUP_MENU_FIND_DEF             40007
#define IDC_BUTTON_CAS                          40008
#define IDC_SHOWBYTE0                           40008
#define IDS_DIS_POPUP_MENU_FIND_REF1            40008
#define IDC_SHOWZPASBYTE                        40009
#define IDS_DIS_POPUP_MENU_FIND_REF2            40009
#define IDC_NONASCIIASBYTES                     40010
#define IDS_DIS_POPUP_MENU_REN_DEF              40010
#define IDC_NUMONLYINBYTE                       40011
#define IDS_DIS_POPUP_MENU_REN_REF              40011
#define IDC_WORDALLOWED                         40012
#define IDS_DIS_TITLE                           40012
#define IDC_SBYTEALLOWED                        40013
#define IDS_DUMP_TITLE_SEGMENT                  40013
#define IDC_ENDFILENAME                         40014
#define IDS_DUMP_TITLE_SEGMENT_NO_SEGMENT_SELECTED 40014
#define IDC_DSALLOWED                           40015
#define IDS_DUMP_TITLE_SELECTION                40015
#define IDC_REMOVEUNUSEDLABELS                  40016
#define IDS_EQUATES_CONFIRM_CLEAR_SYSTEM_EQUATES 40016
#define IDC_INCLUDEALLOWED                      40017
#define IDS_EQUATES_CONFIRM_CLEAR_USER_EQUATES  40017
#define IDC_RADIOINCLUDE_ONE_FILE               40018
#define IDS_ERR_ATARI_FILE                      40018
#define IDC_RADIOINCLUDE_ALL_FILES              40019
#define IDS_ERR_BAD_MODE_FOR_LOHI               40019
#define IDC_RADIOINCLUDE_NEXT_FILE              40020
#define IDS_ERR_BAD_PROFILE                     40020
#define IDS_ERR_BAD_WORKSPACE                   40021
#define ID_LOAD_PROFILE                         40021
#define IDS_ERR_EXCEPTION                       40022
#define ID_SAVE_PROFILE                         40022
#define IDS_ERR_FNT_NOT_FOUND                   40023
#define IDS_ERR_IMG_BAD_MAGIC                   40024
#define IDS_ERR_IMG_DISK_ERROR                  40025
#define IDS_ERR_IMG_FILE_NOT_FOUND              40026
#define IDS_ERR_IMG_OUT_OF_RANGE                40027
#define IDS_ERR_IMG_WRITE_PROTECT               40028
#define IDS_ERR_LABEL_OVEFLOW                   40029
#define IDS_ERR_LOHI_FIRST                      40030
#define IDS_ERR_MULTI_LOHI                      40031
#define IDS_ERR_NO_ATARI_FILE                   40032
#define IDS_ERR_NO_BOOT                         40033
#define IDS_ERR_NO_FREE_SEG                     40034
#define IDS_ERR_NO_GUESS_MEMORY                 40035
#define IDS_EQUATE_LIST_LOADED                  40036
#define IDS_ERR_NO_LABEL_MEMORY                 40037
#define IDS_ERR_NO_SEGMENT                      40038
#define IDS_ERR_READING_ATR                     40039
#define IDS_ERR_READING_FILE                    40040
#define IDS_ERR_SEGMENT_OVERLAP                 40041
#define IDS_EXPORT_USER_EQU                     40042
#define IDS_FILE_IO_EX_OPENING_FILE_FOR_READ_ACCESS 40043
#define IDS_FILE_IO_EX_OPENING_FILE_FOR_WRITE_ACCESS 40044
#define IDS_FILE_IO_ERR_WRITING_FILE            40045
#define IDS_FILE_SYSTEM_LOGIC_OPEN_FILE_TITLE   40046
#define IDS_FILE_SYSTEM_LOGIC_SAVE_FILE_TITLE   40047
#define IDS_FIND_STRING_DIALOG_STRING_NOT_FOUND_MESSAGE 40048
#define IDS_LOG_BETA_MESSAGE                    40049
#define IDS_LOG_DISASSEMBLY_PROGRESS_MONITOR_INFO 40050
#define IDS_LOG_DISASSEMBLY_PROGRESS_MONITOR_PASS 40051
#define IDS_LOG_DISASSEMBLY_PROGRESS_MONITOR_SEGMENT 40052
#define IDS_LOG_OPEN_CASSETTE_FILE              40053
#define IDS_LOG_OPEN_DISK_IMAGE_BOOT_SECTORS    40054
#define IDS_LOG_OPEN_DISK_IMAGE_EXECUTABLE_FILE 40055
#define IDS_LOG_OPEN_DISK_IMAGE_SECTORS         40056
#define IDS_LOG_OPEN_EQUATE_FILE                40057
#define IDS_LOG_OPEN_EXECUTABLE_FILE            40058
#define IDS_LOG_OPEN_PROFILE_FILE               40059
#define IDS_LOG_OPEN_RAW_FILE                   40060
#define IDS_LOG_OPEN_ROM_IMAGE_FILE             40061
#define IDS_LOG_OPEN_WORK                       40062
#define IDS_LOG_SAVE_DISASSEMBLY                40063
#define IDS_LOG_SAVE_EQUATE_FILE                40064
#define IDS_LOG_SAVE_PROFILE_FILE               40065
#define IDS_LOG_SAVE_WORKSPACE_FILE             40066
#define IDS_LOG_SEGMENTS_MERGED                 40067
#define IDS_LOG_TITLE                           40068
#define IDS_MAIN_FILE_LOG_NEW_WORKSPACE_PREPARED 40069
#define IDS_MAIN_FILE_NEW_WORKSPACE_MESSAGE     40070
#define IDS_MAIN_FILE_NEW_WORKSPACE_TITLE       40071
#define IDS_MAIN_FILE_OPEN_WORKSPACE_FILE_MESSAGE 40072
#define IDS_MAIN_FILE_OPEN_WORKSPACE_FILE_TITLE 40073
#define IDS_MAIN_WINDOW_TITLE                   40074
#define IDS_MAIN_WINDOW_TITLE_NO_WORKSPACE_LOADED 40075
#define IDS_SEGMENT_TITLE                       40076
#define IDS_SEGMENT_TITLE_NO_SEGMENTS_LOADED    40077
#define IDS_SPRITE_ANTIC_8                      40078
#define IDS_SPRITE_ANTIC_9                      40079
#define IDS_SPRITE_ANTIC_A                      40080
#define IDS_SPRITE_ANTIC_B                      40081
#define IDS_SPRITE_ANTIC_C                      40082
#define IDS_SPRITE_ANTIC_D                      40083
#define IDS_SPRITE_ANTIC_E                      40084
#define IDS_SPRITE_ANTIC_F                      40085
#define IDS_XREF_TITLE_LABEL_REFERENCE          40086
#define IDS_XREF_TITLE_LABEL_REFERENCES         40087
#define IDS_XREF_TITLE_NO_LABEL_SELECTED        40088
#define IDS_FIND_STRING_DIALOG_TITLE            40089
#define IDS_ERR_CANNOT_PARSE_EQUATE_LINE        40090
#define IDS_FILE_IO_EX_OPENING_FILE_FOR_READ_WRITE_ACCESS 40091
